name: JOSS Paper Check

on:
  push:
    paths:
      - 'paper/**'
  workflow_dispatch:

jobs:
  draft-paper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build Draft Paper
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper/paper.md
